name: CI/CD Pipeline for Node.js with Apache2 and PM2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install react-scripts
        run: |
          cd frontend
          npx react-scripts start

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm run build

      - name: Install PM2
        run: npm install -g pm2

      - name: Start Application with PM2
        run: pm2 start backend/server.js --name "node-app"

      - name: Save PM2 Process
        run: pm2 save

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.KEY }}
          source: "./dist/*"
          target: "/var/www/html"

      - name: Restart PM2 Process
        run: |
          pm2 restart node-app
          pm2 save
